### ISSUE TITLE
Working just once in Android

### ISSUE THREAD

**Issue by carliskisantiago** [ricardoalcocer/socialshare#13]
Hello, I'm writing because we have been using this widget but now we are facing an issue with Android, to be more specific in Android 6. In all other devices work OK but now in Android 6 opens the share dialog just the first time and then simply does nothing. 
We are using Titanium SDK 5.0.2 to avoid problems with runtime permissions. Anyway, we tested the same with SDK 5.2.2. and the problem remains. 
Any help will be great.
Thanks in advance.
Santiago.

**Comment by ricardoalcocer** [comment]
Hi.  Sorry to hear.  I haven't tested on Android 6.  I also don't have time to maintain this module anymore.  My suggestion is to join tislack.org and ask the question there.  If someone shares with you the updated Android code they we can see what the problem is.  A possibility is that Android changed the way you launch the sharing intent, but again, I have no way of testing anymore.
